/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.ContentScore
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 200 : ContentScore (Metadata about the provided URL)
   * 
   * @param url Article URL
   */
  def checkGet(url: String): ApiRequest[ContentScore] =
    ApiRequest[ContentScore](ApiMethods.GET, "https://api.factcheckthe.news/v1", "/check", "text/plain")
      .withQueryParam("url", url)
      .withSuccessResponse[ContentScore](200)
      

}

